<?php

return array(
    'success_added' => 'Added SuccessFully',
    'success_update' => 'Updated Successfully',
    'success_deleted' => 'Deleted Successfully',
    'success_donated' => 'Donated Successfully',
    'unauthenticate'=>'please login ',
    'unAuthorize'=>'User not active ',
    'success_process' => 'Updated Successfully' ,
    'user_not_found'=>'User Not Found',
    'compination_not_found'=>'Compination Not Found',
    'order_not_found'=>'Order Not Found',
    'object_not_found'=>' :name not found',
    'status'=>'Status',
    'price'=>'price',
    'required'=>' :name is required',
    'user'=>'User',
    'employee'=>'Employee',
    'already_existed'=>' :name Already existed',
    'publish_already'=>'Case Already Published',
    'close_case'=>'Case Already Closed ',
    'cancel_case'=>"Case Already Canceld",
    'case_not_completed'=>'Case Not Yet Completed',
    'case'=>'Case',

    'object_not_active'=>' :name  not active',
    'validation_type_related_to_validation'=>'Validation Type Related to Validations',
    'provider_related_to_validation'=>'Provider  Related to Validations ',
    'provider_related_to_cases'=>'Provider  Related to Cases ',
    'country_related_to_users'=>'Country related to users',
    'city_related_to_users'=>'City related to users',
    'images_required'=>"Images is Required" ,
    "Donor"=>"Donor",
    "donor"=>"Donor",
    "not_paid"=>"Not Paid",
    "paid"=>"Paid",

    "wallet_not_enough"=>"Wallet not enough please charge wallet",
    "already_follower"=>"already follow this case",
    "not_follower"=>"you not follow this case"      ,
    'story'=>'Story',
    'full_name'=>'Full Name',
    'secret_name'=> "Secret Name",
    'unique'=>' :name is unique',

    'min'=>'The minimum amount is incomplete',
    'numeric'=>'you must inter integer',
    "draft"=>"Draft1",
    "canceled"=>"Canceled",
    "rejected"=>"Rejected",
    "completed"=>"Completed",
    "closed"=>"Closed",
    "published"=>"Published",
    "paid"=>"Paid",
    "not_paid"=>"Not Paid",
    "Female"=>"Female",
    "Male"=>"`Male",
    "receipt_image"=>"Receipt Image",
    'donation_bigger_remainging'=>":name Has Been Recovered From The Amount Of The Donation Because  OF Complete The Case",
    'ar_name'=>"Arabic Name",
    'country_id'=>"Country",
    'ar_description'=>"Arabic Description",
    'description'=>"Description",
    'type_id'=>"Type",
    'value'=>"Value",

    'case_completed'=>"Case has been completed",
    'case_published'=>"Case has been published",
    'case_locked'=>"Case has been canceled",
    'cover_photo'=>'Cover Photo',
    'case_id'=>'الحالة',


);
